# -*- mode: python ; coding: utf-8 -*-
import sys

block_cipher = None

a = Analysis(
    ['agent_app/launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('static', 'static'),
        ('downloads', 'downloads'),
    ],
    hiddenimports=[
        'backend.main',
        'backend.routes.auth',
        'backend.routes.logs',
        'backend.routes.agents',
        'backend.routes.billing',
        'backend.routes.scanner_features',
        'backend.routes.downloads',
        'backend.database',
        'backend.models',
        'backend.middleware.auth',
        'backend.config',
        'agent.scanners',
        'agent.scanners.prompt_injection',
        'agent.scanners.pii_secrets',
        'agent.scanners.malicious_code',
        'agent.scanners.data_flow',
        'agent.scanners.rogue_agents',
        'agent.scanners.policy_enforcement',
        'agent.scanners.hallucination',
        'agent.scanners.response_safety',
        'agent.scanners.thinking_monitor',
        'agent.scanners.vibe_code_scanner',
        'agent.scanners.vpi',
        'agent.scanners.black_box_ledger',
        'agent.scanners.autonomous_escrow',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'pystray',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'sqlalchemy',
        'sqlalchemy.sql',
        'jose',
        'passlib',
        'passlib.handlers',
        'passlib.handlers.bcrypt',
        'pydantic',
        'pydantic_settings',
        'starlette',
        'multipart',
        'bcrypt',
        'google.auth',
        'google.oauth2',
        'google.auth.transport',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'test', 'unittest'],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AegisAgent',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
